// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.infobip.campus.chattopush.models;

import com.infobip.campus.chattopush.models.UserModel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserModel_Roo_Configurable {
    
    declare @type: UserModel: @Configurable;
    
}
