// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.infobip.campus.rsstopush.models;

import com.infobip.campus.rsstopush.models.PushModel;

privileged aspect PushModel_Roo_JavaBean {
    
    public String PushModel.getTitle() {
        return this.title;
    }
    
    public void PushModel.setTitle(String title) {
        this.title = title;
    }
    
}
