// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.infobip.campus.rsstopush.models;

import com.infobip.campus.rsstopush.models.RssFeedModel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RssFeedModel_Roo_Configurable {
    
    declare @type: RssFeedModel: @Configurable;
    
}
