// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.infobip.campus.rsstopush.models;

import com.infobip.campus.rsstopush.models.RssSourceModel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RssSourceModel_Roo_Configurable {
    
    declare @type: RssSourceModel: @Configurable;
    
}
